# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypto_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryptoWindow(object):
    def setupUi(self, CryptoWindow):
        CryptoWindow.setObjectName("CryptoWindow")
        CryptoWindow.resize(871, 600)
        self.centralwidget = QtWidgets.QWidget(CryptoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passEdit.setFont(font)
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passEdit.setObjectName("passEdit")
        self.horizontalLayout.addWidget(self.passEdit)
        self.passShowButton = QtWidgets.QToolButton(self.centralwidget)
        self.passShowButton.setIconSize(QtCore.QSize(24, 24))
        self.passShowButton.setCheckable(True)
        self.passShowButton.setObjectName("passShowButton")
        self.horizontalLayout.addWidget(self.passShowButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algoBox = QtWidgets.QComboBox(self.centralwidget)
        self.algoBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.algoBox.setFont(font)
        self.algoBox.setObjectName("algoBox")
        self.verticalLayout_2.addWidget(self.algoBox)
        self.modeBox = QtWidgets.QComboBox(self.centralwidget)
        self.modeBox.setObjectName("modeBox")
        self.verticalLayout_2.addWidget(self.modeBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 851, 501))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetSpace = QtWidgets.QVBoxLayout()
        self.widgetSpace.setObjectName("widgetSpace")
        self.gridLayout.addLayout(self.widgetSpace, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        CryptoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CryptoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        CryptoWindow.setMenuBar(self.menubar)
        self.addFile = QtWidgets.QAction(CryptoWindow)
        self.addFile.setObjectName("addFile")
        self.removeFile = QtWidgets.QAction(CryptoWindow)
        self.removeFile.setObjectName("removeFile")
        self.menu.addAction(self.addFile)
        self.menu.addAction(self.removeFile)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(CryptoWindow)
        QtCore.QMetaObject.connectSlotsByName(CryptoWindow)

    def retranslateUi(self, CryptoWindow):
        _translate = QtCore.QCoreApplication.translate
        CryptoWindow.setWindowTitle(_translate("CryptoWindow", "MainWindow"))
        self.passShowButton.setText(_translate("CryptoWindow", "..."))
        self.menu.setTitle(_translate("CryptoWindow", "Файл"))
        self.addFile.setText(_translate("CryptoWindow", "Добавить файл"))
        self.removeFile.setText(_translate("CryptoWindow", "Убрать файл"))
