# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BinMainWindow(object):
    def setupUi(self, BinMainWindow):
        BinMainWindow.setObjectName("BinMainWindow")
        BinMainWindow.resize(971, 210)
        self.centralwidget = QtWidgets.QWidget(BinMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setMaxLength(32)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(600, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.topLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.topLcd.setMinimumSize(QtCore.QSize(300, 0))
        self.topLcd.setDigitCount(10)
        self.topLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.topLcd.setObjectName("topLcd")
        self.horizontalLayout_2.addWidget(self.topLcd)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 4, 1, 1)
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        self.bottomWidget.setObjectName("bottomWidget")
        self.gridLayout.addWidget(self.bottomWidget, 2, 0, 1, 1)
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        self.topWidget.setObjectName("topWidget")
        self.gridLayout.addWidget(self.topWidget, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.bottomLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.bottomLcd.setDigitCount(10)
        self.bottomLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bottomLcd.setObjectName("bottomLcd")
        self.horizontalLayout_3.addWidget(self.bottomLcd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 4, 1, 1)
        BinMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BinMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 21))
        self.menubar.setObjectName("menubar")
        BinMainWindow.setMenuBar(self.menubar)

        self.retranslateUi(BinMainWindow)
        QtCore.QMetaObject.connectSlotsByName(BinMainWindow)

    def retranslateUi(self, BinMainWindow):
        _translate = QtCore.QCoreApplication.translate
        BinMainWindow.setWindowTitle(_translate("BinMainWindow", "Битовые операции"))
        self.pushButton.setText(_translate("BinMainWindow", "Выполнить"))
        self.comboBox.setItemText(0, _translate("BinMainWindow", "Задание 1"))
        self.comboBox.setItemText(1, _translate("BinMainWindow", "Задание 2"))
        self.comboBox.setItemText(2, _translate("BinMainWindow", "Поменять байты"))
        self.comboBox.setItemText(3, _translate("BinMainWindow", "Максимальная степень 2"))
        self.comboBox.setItemText(4, _translate("BinMainWindow", "Найти p: 2^p <= x <= 2^(p+1)"))
        self.comboBox.setItemText(5, _translate("BinMainWindow", "Циклический сдвиг"))
        self.comboBox.setItemText(6, _translate("BinMainWindow", "Перестановка бит"))
        self.label.setText(_translate("BinMainWindow", "="))
        self.label_2.setText(_translate("BinMainWindow", "="))
