# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_part_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondPartWindow(object):
    def setupUi(self, SecondPartWindow):
        SecondPartWindow.setObjectName("SecondPartWindow")
        SecondPartWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SecondPartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit.setFont(font)
        self.line_edit.setObjectName("line_edit")
        self.horizontalLayout.addWidget(self.line_edit)
        self.execute_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.execute_button.setFont(font)
        self.execute_button.setStyleSheet("padding: 4 10")
        self.execute_button.setObjectName("execute_button")
        self.horizontalLayout.addWidget(self.execute_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box.setObjectName("combo_box")
        self.verticalLayout.addWidget(self.combo_box)
        self.plain_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.verticalLayout.addWidget(self.plain_text_edit)
        SecondPartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondPartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        SecondPartWindow.setMenuBar(self.menubar)

        self.retranslateUi(SecondPartWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondPartWindow)

    def retranslateUi(self, SecondPartWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondPartWindow.setWindowTitle(_translate("SecondPartWindow", "Лаба 2"))
        self.execute_button.setText(_translate("SecondPartWindow", "Выполнить"))
